aie_domain: ""

phoenix:
  api_key: ""

nemo:
  namespace: agentic
  guardrail_config_name: demo-self-check-input-output

  main_model:
    engine: nim
    id: ""
    url: ""
    token: ""

  guardrail_model:
    engine: nim
    id: ""
    url: ""
    token: ""