apiVersion: v2
name: model-key-controller
description: A Helm chart for the AIE nemo nim proxy model token controller
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - nim-proxy
  - controller
  - testing
  - debugging
maintainers:
  - name: Alejandro Morales
    email: alemor@hpe.com

