{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "configmap-secret-operator.fullname" . }}-secrets
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "configmap-secret-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
{{- end }}