apiVersion: v2
name: mcp-ezpresto-server
description: A Helm chart for MCP EzPresto Server - To query AIE databases using SQL 
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - mcp
  - sql
  - ezpresto
maintainers:
  - name: Alejandro Morales
    email: alemor@hpe.com

